### ISSUE TITLE
Roadmap to v1.0.0

### ISSUE THREAD

**Issue by changbenny** [changbenny/Spy#4]
- [ ] Add more analytics information. (like mostly hover targets, scroll map, heat map)
- [ ] Add a demo that using  analytics information produce a useful chart.
- [ ] Write tests.
- [ ] Better support for AJAX and dynamic dom manipulation.
